
# Appearance

appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: L

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: false
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

footer:
  copyright:
    notice: 'Â© {year} Sanoop Mallissery. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/git4san/git4san.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: ''
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
